local pack = require("core.pack")

require("plugins.mini").setup(pack)
require("plugins.treesitter").setup(pack)
require("plugins.mdx").setup(pack)
require("plugins.snacks").setup(pack)
require("plugins.lualine").setup(pack)
require("plugins.tmux").setup(pack)
require("plugins.obsidian").setup(pack)
require("plugins.format").setup(pack)
require("plugins.lint").setup(pack)
require("plugins.trouble").setup(pack)
require("plugins.blink").setup(pack)
require("plugins.copilot").setup(pack)
require("plugins.git").setup(pack)
require("plugins.markdown").setup(pack)
require("plugins.tags").setup(pack)
require("plugins.flash").setup(pack)
