personality = "friendly"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"

sandbox_mode = "workspace-write"

notify = ["/Users/charlie/.codex/plugins/cache/openai-bundled/computer-use/1.0.770/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[agents]
max_threads = 10
job_max_runtime_seconds = 3600

[mcp_servers.grep]
url = "https://mcp.grep.app"

[projects."/Users/charlie/Dev/chpeters.me"]
trust_level = "trusted"

[projects."/Users/charlie/.dotfiles"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-19-computer-use-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/charlie/Notes"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-20-use-gmail-plugin-gmail-openai-curated"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-23/computer-use-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-25/create-a-plan-to-migrate-my"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-25/https-brandur-org-newsletter-nanoglyph-is"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-25/https-github-com-yt-dlp-yt"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/New project"]
trust_level = "trusted"

[projects."/Users/charlie/Dev/finance"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-25/i-want-you-to-quiz-me"]
trust_level = "trusted"

[projects."/Users/charlie/Dev/orchestrator"]
trust_level = "trusted"

[projects."/Users/charlie/Dev/codex-annotations.nvim"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-30/use-google-chrome-plugin-computer-use"]
trust_level = "trusted"

[projects."/Users/charlie/Dev/annotator.nvim"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-04-30/open-htis-up-in-this-browser"]
trust_level = "trusted"

[projects."/Users/charlie/Documents/Codex/2026-05-02/use-google-chrome-plugin-computer-use"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-05-01T19:20:25Z"
source_type = "local"
source = "/Users/charlie/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-04-30T19:26:00Z"
source_type = "local"
source = "/Users/charlie/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."expo@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."notion@openai-curated"]
enabled = true

[plugins."vercel@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[features]
memories = true

[memories]
no_memories_if_mcp_or_web_search = false

[sandbox_workspace_write]
network_access = true

[tui.model_availability_nux]
"gpt-5.5" = 1
